import Head from "next/head";
import CTA from "@/components/Modal/CTA";
import { AppStateProvider } from "@/hooks/AppStateContext";
import Forms from "@/components/Modal/Forms";
import Cadastro from "@/components/Forms/Cadastro";
import CompraRapida from "@/components/Buttons/CompraRapida";
import ConfirmarCompra from "@/components/Forms/ConfirmarCompra";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppStateProvider>
          <CompraRapida />
          <CTA />
          <Forms tipo="cadastro" forms={<Cadastro />} />
          <Forms tipo="confirmacao" forms={<ConfirmarCompra />} />
        </AppStateProvider>
      </main>
    </>
  );
}
